### ISSUE TITLE
Missing Legend Entry String

### ISSUE THREAD

**Issue by WDuck** [matlab2tikz/matlab2tikz#854]
This minimum example (Matlab 2015b) generates a stepplot and then the Tikzfile:
```matlab
s=tf('s');
T=1/(s+1);
stepplot(T);
legend('Test Function', 'Location', 'SouthEast');
cleanfigure;
matlab2tikz('stepplot_test.tikz', 'height', '\figureheight', 'width', '\figurewidth');
```

Problem is that the
`\addlegendentry{};`
entry in the tikz file lags of the legends text, so in my Latex document the legend appears but with no explanation.
Workaround is adding the Text manually into the tikz file but with more the two graphs it will be an annoying thing to do....
I tried to track down the problem and solve it by myself but with no success.
`findLegendInformation(m2t, child)` inside `handleAllChildren` seems to find the "DisplayName" but then it occurs the case were `drawHggroup` is called and that again calls  due to ` case {'hggroup', 'matlab.graphics.primitive.Group'}` again `[m2t, str] = handleAllChildren(m2t, h)`...and that is where I got lost.
Please, can anyone confirm the bug and/or fix it?

Kind Regards,
Philipp

**Comment by miscco** [comment]
Hi, when run you MWE, then i get the following
```latex
% This file was created by matlab2tikz.
%
%The latest updates can be retrieved from
%  http://www.mathworks.com/matlabcentral/fileexchange/22022-matlab2tikz-matlab2tikz
%where you can also make suggestions and rate matlab2tikz.
%
\definecolor{mycolor1}{rgb}{0.00000,0.44700,0.74100}%
%
\begin{tikzpicture}

\begin{axis}[%
width=0.925\figurewidth,
height=0.942\figureheight,
at={(0.026\figurewidth,0\figureheight)},
scale only axis,
separate axis lines,
every outer x axis line/.append style={white!40!black},
every x tick label/.append style={font=\color{white!40!black}},
xmin=0,
xmax=9,
every outer y axis line/.append style={white!40!black},
every y tick label/.append style={font=\color{white!40!black}},
ymin=0,
ymax=1,
axis background/.style={fill=white},
legend style={at={(0.97,0.03)},anchor=south east,legend cell align=left,align=left,draw=white!15!black}
]
\addplot [color=mycolor1,solid,forget plot]
  table[row sep=crcr]{%
0	0\\
0.0460517018598701	0.0450074139785546\\
snip
9.02613356453466	0.999879773556536\\
};
\addlegendentry{Test Function};

\addplot [color=black,dotted,forget plot]
  table[row sep=crcr]{%
-0.9	1\\
9.89999999999998	1\\
};
\end{axis}

\begin{axis}[%
width=0.951\figurewidth,
height=\figureheight,
at={(0\figurewidth,0\figureheight)},
scale only axis,
xmin=0,
xmax=1,
xtick={\empty},
xlabel={Time (seconds)},
ymin=0,
ymax=1,
ytick={\empty},
ylabel={Amplitude},
hide axis,
title style={font=\bfseries},
title={Step Response},
axis x line*=bottom,
axis y line*=left
]
\end{axis}
\end{tikzpicture}%
```

So the legendenty is not empty, therefore i assume, the problem seems to be on your side

**Comment by miscco** [comment]
Did you pul the latest develop branch of m2t? It might be that master has a problem there

**Comment by okomarov** [comment]
@WDuck Please try to update your `matlab2tikz` version with our development distribution, i.e. from https://github.com/matlab2tikz/matlab2tikz/tree/develop "download the zip".

**Comment by WDuck** [comment]
Jep, that was it. Thank you!
Shame on me that I hadn't the idea by myself, sory for taking your time!

**Comment by egeerardyn** [comment]
@WDuck Thank you for the detailed bug report! I can confirm this bug in the `master` branch (i.e. what you download from FileExchange) and it has been solved in the current `develop` already (verified in R2016a-PR).

**Comment by egeerardyn** [comment]
@WDuck: don't worry :smile: I love such complete bug reports (and bugs that are already solved but not released on FileExchange is something that is my bad, not yours)

**Comment by miscco** [comment]
@egeerardyn Given that m2t has gone a long way since 1.0 we might want to think about a 1.1 release.

**Comment by egeerardyn** [comment]
@miscco absolutely, however, I think we really need to have a look at the issues left for the 1.1 milestone since there are some parts of the current develop that are not yet production ready.

**Comment by rezahousseini** [comment]
I still have this problem when overlaying multiple figures with hold on, hold off. I'm at the newest develop branch.

**Comment by egeerardyn** [comment]
@rezahousseini Please open a new issue report with MATLAB code that reproduces the problem.
